/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import type {
  ProblemDetails,
  ProductImportResult,
  UploadProductImportJsonBody,
  UploadProductImportJsonParams,
} from '.././model';
import { orvalApiClient } from '.././api-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Example of contract: {
  "shop_id": 2,
  "shop_name": "Billa",
  "shop_location": "Muchovo námestie",
  "timestamp": 1772009877.8182416,
  "num_products": 1,
  "valid_from": "2026-02-25",
  "valid_to": "2026-02-26",
  "products": [
    {
      "barcode": "9008684055027",
      "category_id": null,
      "product": "NICE BITES Mandle v horkej čokoláde 130g",
      "brand": null,
      "price": 3.39,
      "original_price": 3.39,
      "amount": 1.0,
      "unit": "pcs",
      "normalized_price": null,
      "normalized_original_price": null,
      "valid_from": null,
      "valid_to": null
    }
  ]
}
 * @summary Upload Products scrape JSON File
 */
export const uploadProductImportJson = (
  uploadProductImportJsonBody: UploadProductImportJsonBody,
  params?: UploadProductImportJsonParams,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  if (uploadProductImportJsonBody.jsonFile !== undefined) {
    formData.append('jsonFile', uploadProductImportJsonBody.jsonFile);
  }

  return orvalApiClient<ProductImportResult>(
    {
      url: `/admin/wolt-imports`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      params,
      signal,
    },
    options,
  );
};

export const getUploadProductImportJsonMutationOptions = <
  TData = Awaited<ReturnType<typeof uploadProductImportJson>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    {
      data: UploadProductImportJsonBody;
      params?: UploadProductImportJsonParams;
    },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['uploadProductImportJson'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadProductImportJson>>,
    {
      data: UploadProductImportJsonBody;
      params?: UploadProductImportJsonParams;
    }
  > = props => {
    const { data, params } = props ?? {};

    return uploadProductImportJson(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    {
      data: UploadProductImportJsonBody;
      params?: UploadProductImportJsonParams;
    },
    TContext
  >;
};

export type UploadProductImportJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadProductImportJson>>
>;
export type UploadProductImportJsonMutationBody = UploadProductImportJsonBody;
export type UploadProductImportJsonMutationError = ProblemDetails;

/**
 * @summary Upload Products scrape JSON File
 */
export const useUploadProductImportJson = <
  TData = Awaited<ReturnType<typeof uploadProductImportJson>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    {
      data: UploadProductImportJsonBody;
      params?: UploadProductImportJsonParams;
    },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<
  TData,
  TError,
  { data: UploadProductImportJsonBody; params?: UploadProductImportJsonParams },
  TContext
> => {
  const mutationOptions = getUploadProductImportJsonMutationOptions(options);

  return useMutation(mutationOptions);
};
