/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import type {
  DiscountPriceImportBatchDto,
  UploadDiscountPricesAdminJsonBody,
} from '.././model';
import { orvalApiClient } from '.././api-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const uploadDiscountPricesAdminJson = (
  uploadDiscountPricesAdminJsonBody: UploadDiscountPricesAdminJsonBody,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  if (uploadDiscountPricesAdminJsonBody.jsonFile !== undefined) {
    formData.append('jsonFile', uploadDiscountPricesAdminJsonBody.jsonFile);
  }

  return orvalApiClient<DiscountPriceImportBatchDto>(
    {
      url: `/admin/wolt-imports`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options,
  );
};

export const getUploadDiscountPricesAdminJsonMutationOptions = <
  TData = Awaited<ReturnType<typeof uploadDiscountPricesAdminJson>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: UploadDiscountPricesAdminJsonBody },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['uploadDiscountPricesAdminJson'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadDiscountPricesAdminJson>>,
    { data: UploadDiscountPricesAdminJsonBody }
  > = (props) => {
    const { data } = props ?? {};

    return uploadDiscountPricesAdminJson(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: UploadDiscountPricesAdminJsonBody },
    TContext
  >;
};

export type UploadDiscountPricesAdminJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadDiscountPricesAdminJson>>
>;
export type UploadDiscountPricesAdminJsonMutationBody =
  UploadDiscountPricesAdminJsonBody;
export type UploadDiscountPricesAdminJsonMutationError = unknown;

export const useUploadDiscountPricesAdminJson = <
  TData = Awaited<ReturnType<typeof uploadDiscountPricesAdminJson>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: UploadDiscountPricesAdminJsonBody },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<
  TData,
  TError,
  { data: UploadDiscountPricesAdminJsonBody },
  TContext
> => {
  const mutationOptions =
    getUploadDiscountPricesAdminJsonMutationOptions(options);

  return useMutation(mutationOptions);
};
