/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  AddCategoryRequest,
  AddMasterProductRequest,
  AddOrChangePriceBulkRequest,
  AddOrChangePriceRequest,
  AddProductAdminRequest,
  AddShopRequest,
  AddShopResponse,
  BulkUpdateRequest,
  GetCategoriesAdminParams,
  GetCategoryAdminResponse,
  GetProductPricesResponse,
  GetProductsAdminParams,
  GetProductsAdminResponse,
  GetShopsAdminResponse,
  GetShopsStatsParams,
  GetShopsStatsResponse,
  PatchCategoryRequest,
  PatchProductRequest,
  PatchProductResponse,
  ProblemDetails,
  ProductDto,
  UpdateShopRequest,
  _ExportParams,
} from '.././model';
import { orvalApiClient } from '.././api-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const addShop = (
  addShopRequest: AddShopRequest,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<AddShopResponse>(
    {
      url: `/admin/shops`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addShopRequest,
      signal,
    },
    options,
  );
};

export const getAddShopMutationOptions = <
  TData = Awaited<ReturnType<typeof addShop>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: AddShopRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['addShop'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addShop>>,
    { data: AddShopRequest }
  > = props => {
    const { data } = props ?? {};

    return addShop(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: AddShopRequest },
    TContext
  >;
};

export type AddShopMutationResult = NonNullable<
  Awaited<ReturnType<typeof addShop>>
>;
export type AddShopMutationBody = AddShopRequest;
export type AddShopMutationError = ProblemDetails;

export const useAddShop = <
  TData = Awaited<ReturnType<typeof addShop>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: AddShopRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<TData, TError, { data: AddShopRequest }, TContext> => {
  const mutationOptions = getAddShopMutationOptions(options);

  return useMutation(mutationOptions);
};
export const adminGetShops = (
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<GetShopsAdminResponse>(
    { url: `/admin/shops`, method: 'GET', signal },
    options,
  );
};

export const getAdminGetShopsQueryKey = () => {
  return [`/admin/shops`] as const;
};

export const getAdminGetShopsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetShops>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof adminGetShops>>, TError, TData>
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetShopsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetShops>>> = ({
    signal,
  }) => adminGetShops(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetShops>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminGetShopsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetShops>>
>;
export type AdminGetShopsQueryError = ProblemDetails;

export function useAdminGetShops<
  TData = Awaited<ReturnType<typeof adminGetShops>>,
  TError = ProblemDetails,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof adminGetShops>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof adminGetShops>>,
        TError,
        TData
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof orvalApiClient>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminGetShops<
  TData = Awaited<ReturnType<typeof adminGetShops>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof adminGetShops>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof adminGetShops>>,
        TError,
        TData
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminGetShops<
  TData = Awaited<ReturnType<typeof adminGetShops>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof adminGetShops>>, TError, TData>
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAdminGetShops<
  TData = Awaited<ReturnType<typeof adminGetShops>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof adminGetShops>>, TError, TData>
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminGetShopsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateShop = (
  shopId: number,
  options?: SecondParameter<typeof orvalApiClient>,
) => {
  return orvalApiClient<void>(
    { url: `/admin/shops/${shopId}`, method: 'DELETE' },
    options,
  );
};

export const getUpdateShopMutationOptions = <
  TData = Awaited<ReturnType<typeof updateShop>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { shopId: number }, TContext>;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['updateShop'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateShop>>,
    { shopId: number }
  > = props => {
    const { shopId } = props ?? {};

    return updateShop(shopId, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { shopId: number },
    TContext
  >;
};

export type UpdateShopMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateShop>>
>;

export type UpdateShopMutationError = ProblemDetails;

export const useUpdateShop = <
  TData = Awaited<ReturnType<typeof updateShop>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { shopId: number }, TContext>;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<TData, TError, { shopId: number }, TContext> => {
  const mutationOptions = getUpdateShopMutationOptions(options);

  return useMutation(mutationOptions);
};
export const patchShop = (
  shopId: number,
  updateShopRequest: UpdateShopRequest,
  options?: SecondParameter<typeof orvalApiClient>,
) => {
  return orvalApiClient<void>(
    {
      url: `/admin/shops/${shopId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateShopRequest,
    },
    options,
  );
};

export const getPatchShopMutationOptions = <
  TData = Awaited<ReturnType<typeof patchShop>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { shopId: number; data: UpdateShopRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['patchShop'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchShop>>,
    { shopId: number; data: UpdateShopRequest }
  > = props => {
    const { shopId, data } = props ?? {};

    return patchShop(shopId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { shopId: number; data: UpdateShopRequest },
    TContext
  >;
};

export type PatchShopMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchShop>>
>;
export type PatchShopMutationBody = UpdateShopRequest;
export type PatchShopMutationError = ProblemDetails;

export const usePatchShop = <
  TData = Awaited<ReturnType<typeof patchShop>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { shopId: number; data: UpdateShopRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<
  TData,
  TError,
  { shopId: number; data: UpdateShopRequest },
  TContext
> => {
  const mutationOptions = getPatchShopMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getShopsStats = (
  shopId: number,
  params?: GetShopsStatsParams,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<GetShopsStatsResponse>(
    { url: `/admin/shops/${shopId}/categories`, method: 'GET', params, signal },
    options,
  );
};

export const getGetShopsStatsQueryKey = (
  shopId: number,
  params?: GetShopsStatsParams,
) => {
  return [
    `/admin/shops/${shopId}/categories`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetShopsStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getShopsStats>>,
  TError = ProblemDetails,
>(
  shopId: number,
  params?: GetShopsStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getShopsStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetShopsStatsQueryKey(shopId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getShopsStats>>> = ({
    signal,
  }) => getShopsStats(shopId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!shopId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getShopsStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetShopsStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getShopsStats>>
>;
export type GetShopsStatsQueryError = ProblemDetails;

export function useGetShopsStats<
  TData = Awaited<ReturnType<typeof getShopsStats>>,
  TError = ProblemDetails,
>(
  shopId: number,
  params: undefined | GetShopsStatsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getShopsStats>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShopsStats>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetShopsStats<
  TData = Awaited<ReturnType<typeof getShopsStats>>,
  TError = ProblemDetails,
>(
  shopId: number,
  params?: GetShopsStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getShopsStats>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShopsStats>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetShopsStats<
  TData = Awaited<ReturnType<typeof getShopsStats>>,
  TError = ProblemDetails,
>(
  shopId: number,
  params?: GetShopsStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getShopsStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetShopsStats<
  TData = Awaited<ReturnType<typeof getShopsStats>>,
  TError = ProblemDetails,
>(
  shopId: number,
  params?: GetShopsStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getShopsStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetShopsStatsQueryOptions(shopId, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const addProductAdmin = (
  addProductAdminRequest: AddProductAdminRequest,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<ProductDto>(
    {
      url: `/admin/products`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addProductAdminRequest,
      signal,
    },
    options,
  );
};

export const getAddProductAdminMutationOptions = <
  TData = Awaited<ReturnType<typeof addProductAdmin>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: AddProductAdminRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['addProductAdmin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addProductAdmin>>,
    { data: AddProductAdminRequest }
  > = props => {
    const { data } = props ?? {};

    return addProductAdmin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: AddProductAdminRequest },
    TContext
  >;
};

export type AddProductAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof addProductAdmin>>
>;
export type AddProductAdminMutationBody = AddProductAdminRequest;
export type AddProductAdminMutationError = ProblemDetails;

export const useAddProductAdmin = <
  TData = Awaited<ReturnType<typeof addProductAdmin>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: AddProductAdminRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<
  TData,
  TError,
  { data: AddProductAdminRequest },
  TContext
> => {
  const mutationOptions = getAddProductAdminMutationOptions(options);

  return useMutation(mutationOptions);
};
export const bulkPatchProductAdmin = (
  bulkUpdateRequest: BulkUpdateRequest,
  options?: SecondParameter<typeof orvalApiClient>,
) => {
  return orvalApiClient<void>(
    {
      url: `/admin/products`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: bulkUpdateRequest,
    },
    options,
  );
};

export const getBulkPatchProductAdminMutationOptions = <
  TData = Awaited<ReturnType<typeof bulkPatchProductAdmin>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: BulkUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['bulkPatchProductAdmin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bulkPatchProductAdmin>>,
    { data: BulkUpdateRequest }
  > = props => {
    const { data } = props ?? {};

    return bulkPatchProductAdmin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: BulkUpdateRequest },
    TContext
  >;
};

export type BulkPatchProductAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof bulkPatchProductAdmin>>
>;
export type BulkPatchProductAdminMutationBody = BulkUpdateRequest;
export type BulkPatchProductAdminMutationError = ProblemDetails;

export const useBulkPatchProductAdmin = <
  TData = Awaited<ReturnType<typeof bulkPatchProductAdmin>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: BulkUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<TData, TError, { data: BulkUpdateRequest }, TContext> => {
  const mutationOptions = getBulkPatchProductAdminMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getProductsAdmin = (
  params?: GetProductsAdminParams,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<GetProductsAdminResponse>(
    { url: `/admin/products`, method: 'GET', params, signal },
    options,
  );
};

export const getGetProductsAdminQueryKey = (
  params?: GetProductsAdminParams,
) => {
  return [`/admin/products`, ...(params ? [params] : [])] as const;
};

export const getGetProductsAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getProductsAdmin>>,
  TError = ProblemDetails,
>(
  params?: GetProductsAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductsAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProductsAdminQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProductsAdmin>>
  > = ({ signal }) => getProductsAdmin(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProductsAdmin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProductsAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProductsAdmin>>
>;
export type GetProductsAdminQueryError = ProblemDetails;

export function useGetProductsAdmin<
  TData = Awaited<ReturnType<typeof getProductsAdmin>>,
  TError = ProblemDetails,
>(
  params: undefined | GetProductsAdminParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductsAdmin>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsAdmin>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProductsAdmin<
  TData = Awaited<ReturnType<typeof getProductsAdmin>>,
  TError = ProblemDetails,
>(
  params?: GetProductsAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductsAdmin>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsAdmin>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProductsAdmin<
  TData = Awaited<ReturnType<typeof getProductsAdmin>>,
  TError = ProblemDetails,
>(
  params?: GetProductsAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductsAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetProductsAdmin<
  TData = Awaited<ReturnType<typeof getProductsAdmin>>,
  TError = ProblemDetails,
>(
  params?: GetProductsAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductsAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProductsAdminQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteProductAdmin = (
  productId: number,
  options?: SecondParameter<typeof orvalApiClient>,
) => {
  return orvalApiClient<void>(
    { url: `/admin/products/${productId}`, method: 'DELETE' },
    options,
  );
};

export const getDeleteProductAdminMutationOptions = <
  TData = Awaited<ReturnType<typeof deleteProductAdmin>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { productId: number }, TContext>;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['deleteProductAdmin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProductAdmin>>,
    { productId: number }
  > = props => {
    const { productId } = props ?? {};

    return deleteProductAdmin(productId, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { productId: number },
    TContext
  >;
};

export type DeleteProductAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteProductAdmin>>
>;

export type DeleteProductAdminMutationError = ProblemDetails;

export const useDeleteProductAdmin = <
  TData = Awaited<ReturnType<typeof deleteProductAdmin>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { productId: number }, TContext>;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<TData, TError, { productId: number }, TContext> => {
  const mutationOptions = getDeleteProductAdminMutationOptions(options);

  return useMutation(mutationOptions);
};
export const patchProductAdmin = (
  productId: number,
  patchProductRequest: PatchProductRequest,
  options?: SecondParameter<typeof orvalApiClient>,
) => {
  return orvalApiClient<PatchProductResponse>(
    {
      url: `/admin/products/${productId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchProductRequest,
    },
    options,
  );
};

export const getPatchProductAdminMutationOptions = <
  TData = Awaited<ReturnType<typeof patchProductAdmin>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { productId: number; data: PatchProductRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['patchProductAdmin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchProductAdmin>>,
    { productId: number; data: PatchProductRequest }
  > = props => {
    const { productId, data } = props ?? {};

    return patchProductAdmin(productId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { productId: number; data: PatchProductRequest },
    TContext
  >;
};

export type PatchProductAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchProductAdmin>>
>;
export type PatchProductAdminMutationBody = PatchProductRequest;
export type PatchProductAdminMutationError = ProblemDetails;

export const usePatchProductAdmin = <
  TData = Awaited<ReturnType<typeof patchProductAdmin>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { productId: number; data: PatchProductRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<
  TData,
  TError,
  { productId: number; data: PatchProductRequest },
  TContext
> => {
  const mutationOptions = getPatchProductAdminMutationOptions(options);

  return useMutation(mutationOptions);
};
export const _export = (
  params?: _ExportParams,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<void>(
    { url: `/admin/products/export`, method: 'GET', params, signal },
    options,
  );
};

export const getExportQueryKey = (params?: _ExportParams) => {
  return [`/admin/products/export`, ...(params ? [params] : [])] as const;
};

export const getExportQueryOptions = <
  TData = Awaited<ReturnType<typeof _export>>,
  TError = unknown,
>(
  params?: _ExportParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getExportQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof _export>>> = ({
    signal,
  }) => _export(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof _export>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type _ExportQueryResult = NonNullable<
  Awaited<ReturnType<typeof _export>>
>;
export type _ExportQueryError = unknown;

export function useExport<
  TData = Awaited<ReturnType<typeof _export>>,
  TError = unknown,
>(
  params: undefined | _ExportParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof _export>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExport<
  TData = Awaited<ReturnType<typeof _export>>,
  TError = unknown,
>(
  params?: _ExportParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof _export>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExport<
  TData = Awaited<ReturnType<typeof _export>>,
  TError = unknown,
>(
  params?: _ExportParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useExport<
  TData = Awaited<ReturnType<typeof _export>>,
  TError = unknown,
>(
  params?: _ExportParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExportQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const addOrChangePriceBulk = (
  addOrChangePriceBulkRequest: AddOrChangePriceBulkRequest,
  options?: SecondParameter<typeof orvalApiClient>,
) => {
  return orvalApiClient<void>(
    {
      url: `/admin/products/prices`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: addOrChangePriceBulkRequest,
    },
    options,
  );
};

export const getAddOrChangePriceBulkMutationOptions = <
  TData = Awaited<ReturnType<typeof addOrChangePriceBulk>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: AddOrChangePriceBulkRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['addOrChangePriceBulk'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addOrChangePriceBulk>>,
    { data: AddOrChangePriceBulkRequest }
  > = props => {
    const { data } = props ?? {};

    return addOrChangePriceBulk(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: AddOrChangePriceBulkRequest },
    TContext
  >;
};

export type AddOrChangePriceBulkMutationResult = NonNullable<
  Awaited<ReturnType<typeof addOrChangePriceBulk>>
>;
export type AddOrChangePriceBulkMutationBody = AddOrChangePriceBulkRequest;
export type AddOrChangePriceBulkMutationError = ProblemDetails;

export const useAddOrChangePriceBulk = <
  TData = Awaited<ReturnType<typeof addOrChangePriceBulk>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: AddOrChangePriceBulkRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<
  TData,
  TError,
  { data: AddOrChangePriceBulkRequest },
  TContext
> => {
  const mutationOptions = getAddOrChangePriceBulkMutationOptions(options);

  return useMutation(mutationOptions);
};
export const addOrChangePrice = (
  productId: number,
  addOrChangePriceRequest: AddOrChangePriceRequest,
  options?: SecondParameter<typeof orvalApiClient>,
) => {
  return orvalApiClient<void>(
    {
      url: `/admin/products/${productId}/prices`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: addOrChangePriceRequest,
    },
    options,
  );
};

export const getAddOrChangePriceMutationOptions = <
  TData = Awaited<ReturnType<typeof addOrChangePrice>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { productId: number; data: AddOrChangePriceRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['addOrChangePrice'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addOrChangePrice>>,
    { productId: number; data: AddOrChangePriceRequest }
  > = props => {
    const { productId, data } = props ?? {};

    return addOrChangePrice(productId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { productId: number; data: AddOrChangePriceRequest },
    TContext
  >;
};

export type AddOrChangePriceMutationResult = NonNullable<
  Awaited<ReturnType<typeof addOrChangePrice>>
>;
export type AddOrChangePriceMutationBody = AddOrChangePriceRequest;
export type AddOrChangePriceMutationError = ProblemDetails;

export const useAddOrChangePrice = <
  TData = Awaited<ReturnType<typeof addOrChangePrice>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { productId: number; data: AddOrChangePriceRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<
  TData,
  TError,
  { productId: number; data: AddOrChangePriceRequest },
  TContext
> => {
  const mutationOptions = getAddOrChangePriceMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getProductPrices = (
  productId: number,
  shopId: number,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<GetProductPricesResponse>(
    {
      url: `/admin/products/${productId}/prices/${shopId}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getGetProductPricesQueryKey = (
  productId: number,
  shopId: number,
) => {
  return [`/admin/products/${productId}/prices/${shopId}`] as const;
};

export const getGetProductPricesQueryOptions = <
  TData = Awaited<ReturnType<typeof getProductPrices>>,
  TError = ProblemDetails,
>(
  productId: number,
  shopId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductPrices>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProductPricesQueryKey(productId, shopId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProductPrices>>
  > = ({ signal }) =>
    getProductPrices(productId, shopId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(productId && shopId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProductPrices>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProductPricesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProductPrices>>
>;
export type GetProductPricesQueryError = ProblemDetails;

export function useGetProductPrices<
  TData = Awaited<ReturnType<typeof getProductPrices>>,
  TError = ProblemDetails,
>(
  productId: number,
  shopId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductPrices>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductPrices>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProductPrices<
  TData = Awaited<ReturnType<typeof getProductPrices>>,
  TError = ProblemDetails,
>(
  productId: number,
  shopId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductPrices>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductPrices>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProductPrices<
  TData = Awaited<ReturnType<typeof getProductPrices>>,
  TError = ProblemDetails,
>(
  productId: number,
  shopId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductPrices>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetProductPrices<
  TData = Awaited<ReturnType<typeof getProductPrices>>,
  TError = ProblemDetails,
>(
  productId: number,
  shopId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductPrices>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProductPricesQueryOptions(
    productId,
    shopId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const addMasterProduct = (
  addMasterProductRequest: AddMasterProductRequest,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<void>(
    {
      url: `/admin/master-products`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addMasterProductRequest,
      signal,
    },
    options,
  );
};

export const getAddMasterProductMutationOptions = <
  TData = Awaited<ReturnType<typeof addMasterProduct>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: AddMasterProductRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['addMasterProduct'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addMasterProduct>>,
    { data: AddMasterProductRequest }
  > = props => {
    const { data } = props ?? {};

    return addMasterProduct(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: AddMasterProductRequest },
    TContext
  >;
};

export type AddMasterProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof addMasterProduct>>
>;
export type AddMasterProductMutationBody = AddMasterProductRequest;
export type AddMasterProductMutationError = ProblemDetails;

export const useAddMasterProduct = <
  TData = Awaited<ReturnType<typeof addMasterProduct>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: AddMasterProductRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<
  TData,
  TError,
  { data: AddMasterProductRequest },
  TContext
> => {
  const mutationOptions = getAddMasterProductMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getMasterProduct = (
  id: number,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<void>(
    { url: `/admin/master-products/${id}`, method: 'GET', signal },
    options,
  );
};

export const getGetMasterProductQueryKey = (id: number) => {
  return [`/admin/master-products/${id}`] as const;
};

export const getGetMasterProductQueryOptions = <
  TData = Awaited<ReturnType<typeof getMasterProduct>>,
  TError = ProblemDetails,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMasterProduct>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterProductQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMasterProduct>>
  > = ({ signal }) => getMasterProduct(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMasterProduct>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterProductQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMasterProduct>>
>;
export type GetMasterProductQueryError = ProblemDetails;

export function useGetMasterProduct<
  TData = Awaited<ReturnType<typeof getMasterProduct>>,
  TError = ProblemDetails,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMasterProduct>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMasterProduct>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMasterProduct<
  TData = Awaited<ReturnType<typeof getMasterProduct>>,
  TError = ProblemDetails,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMasterProduct>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMasterProduct>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMasterProduct<
  TData = Awaited<ReturnType<typeof getMasterProduct>>,
  TError = ProblemDetails,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMasterProduct>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetMasterProduct<
  TData = Awaited<ReturnType<typeof getMasterProduct>>,
  TError = ProblemDetails,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMasterProduct>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMasterProductQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const resolveMasterProduct = (
  id: number,
  options?: SecondParameter<typeof orvalApiClient>,
) => {
  return orvalApiClient<void>(
    { url: `/admin/resolve-master-products/${id}`, method: 'PUT' },
    options,
  );
};

export const getResolveMasterProductMutationOptions = <
  TData = Awaited<ReturnType<typeof resolveMasterProduct>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: number }, TContext>;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['resolveMasterProduct'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resolveMasterProduct>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return resolveMasterProduct(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { id: number },
    TContext
  >;
};

export type ResolveMasterProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof resolveMasterProduct>>
>;

export type ResolveMasterProductMutationError = ProblemDetails;

export const useResolveMasterProduct = <
  TData = Awaited<ReturnType<typeof resolveMasterProduct>>,
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: number }, TContext>;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<TData, TError, { id: number }, TContext> => {
  const mutationOptions = getResolveMasterProductMutationOptions(options);

  return useMutation(mutationOptions);
};
export const addCategory = (
  addCategoryRequest: AddCategoryRequest,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<void>(
    {
      url: `/admin/categories`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addCategoryRequest,
      signal,
    },
    options,
  );
};

export const getAddCategoryMutationOptions = <
  TData = Awaited<ReturnType<typeof addCategory>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: AddCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['addCategory'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addCategory>>,
    { data: AddCategoryRequest }
  > = props => {
    const { data } = props ?? {};

    return addCategory(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: AddCategoryRequest },
    TContext
  >;
};

export type AddCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof addCategory>>
>;
export type AddCategoryMutationBody = AddCategoryRequest;
export type AddCategoryMutationError = unknown;

export const useAddCategory = <
  TData = Awaited<ReturnType<typeof addCategory>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: AddCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<
  TData,
  TError,
  { data: AddCategoryRequest },
  TContext
> => {
  const mutationOptions = getAddCategoryMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getCategoriesAdmin = (
  params?: GetCategoriesAdminParams,
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<GetCategoryAdminResponse>(
    { url: `/admin/categories`, method: 'GET', params, signal },
    options,
  );
};

export const getGetCategoriesAdminQueryKey = (
  params?: GetCategoriesAdminParams,
) => {
  return [`/admin/categories`, ...(params ? [params] : [])] as const;
};

export const getGetCategoriesAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getCategoriesAdmin>>,
  TError = ProblemDetails,
>(
  params?: GetCategoriesAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoriesAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCategoriesAdminQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCategoriesAdmin>>
  > = ({ signal }) => getCategoriesAdmin(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCategoriesAdmin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCategoriesAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCategoriesAdmin>>
>;
export type GetCategoriesAdminQueryError = ProblemDetails;

export function useGetCategoriesAdmin<
  TData = Awaited<ReturnType<typeof getCategoriesAdmin>>,
  TError = ProblemDetails,
>(
  params: undefined | GetCategoriesAdminParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoriesAdmin>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoriesAdmin>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCategoriesAdmin<
  TData = Awaited<ReturnType<typeof getCategoriesAdmin>>,
  TError = ProblemDetails,
>(
  params?: GetCategoriesAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoriesAdmin>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoriesAdmin>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCategoriesAdmin<
  TData = Awaited<ReturnType<typeof getCategoriesAdmin>>,
  TError = ProblemDetails,
>(
  params?: GetCategoriesAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoriesAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCategoriesAdmin<
  TData = Awaited<ReturnType<typeof getCategoriesAdmin>>,
  TError = ProblemDetails,
>(
  params?: GetCategoriesAdminParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoriesAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCategoriesAdminQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteCategory = (
  categoryId: number,
  options?: SecondParameter<typeof orvalApiClient>,
) => {
  return orvalApiClient<void>(
    { url: `/admin/categories/${categoryId}`, method: 'DELETE' },
    options,
  );
};

export const getDeleteCategoryMutationOptions = <
  TData = Awaited<ReturnType<typeof deleteCategory>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { categoryId: number },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['deleteCategory'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCategory>>,
    { categoryId: number }
  > = props => {
    const { categoryId } = props ?? {};

    return deleteCategory(categoryId, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { categoryId: number },
    TContext
  >;
};

export type DeleteCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCategory>>
>;

export type DeleteCategoryMutationError = unknown;

export const useDeleteCategory = <
  TData = Awaited<ReturnType<typeof deleteCategory>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { categoryId: number },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<TData, TError, { categoryId: number }, TContext> => {
  const mutationOptions = getDeleteCategoryMutationOptions(options);

  return useMutation(mutationOptions);
};
export const patchCategory = (
  categoryId: number,
  patchCategoryRequest: PatchCategoryRequest,
  options?: SecondParameter<typeof orvalApiClient>,
) => {
  return orvalApiClient<void>(
    {
      url: `/admin/categories/${categoryId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchCategoryRequest,
    },
    options,
  );
};

export const getPatchCategoryMutationOptions = <
  TData = Awaited<ReturnType<typeof patchCategory>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { categoryId: number; data: PatchCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const mutationKey = ['patchCategory'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchCategory>>,
    { categoryId: number; data: PatchCategoryRequest }
  > = props => {
    const { categoryId, data } = props ?? {};

    return patchCategory(categoryId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { categoryId: number; data: PatchCategoryRequest },
    TContext
  >;
};

export type PatchCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchCategory>>
>;
export type PatchCategoryMutationBody = PatchCategoryRequest;
export type PatchCategoryMutationError = unknown;

export const usePatchCategory = <
  TData = Awaited<ReturnType<typeof patchCategory>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { categoryId: number; data: PatchCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationResult<
  TData,
  TError,
  { categoryId: number; data: PatchCategoryRequest },
  TContext
> => {
  const mutationOptions = getPatchCategoryMutationOptions(options);

  return useMutation(mutationOptions);
};
export const exportCategories = (
  options?: SecondParameter<typeof orvalApiClient>,
  signal?: AbortSignal,
) => {
  return orvalApiClient<void>(
    { url: `/admin/categories/export`, method: 'GET', signal },
    options,
  );
};

export const getExportCategoriesQueryKey = () => {
  return [`/admin/categories/export`] as const;
};

export const getExportCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof exportCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof exportCategories>>, TError, TData>
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getExportCategoriesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof exportCategories>>
  > = ({ signal }) => exportCategories(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof exportCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExportCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof exportCategories>>
>;
export type ExportCategoriesQueryError = unknown;

export function useExportCategories<
  TData = Awaited<ReturnType<typeof exportCategories>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof exportCategories>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof exportCategories>>,
        TError,
        TData
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof orvalApiClient>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportCategories<
  TData = Awaited<ReturnType<typeof exportCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof exportCategories>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof exportCategories>>,
        TError,
        TData
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportCategories<
  TData = Awaited<ReturnType<typeof exportCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof exportCategories>>, TError, TData>
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useExportCategories<
  TData = Awaited<ReturnType<typeof exportCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof exportCategories>>, TError, TData>
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExportCategoriesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
