/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface AddCategoryDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  image_url?: string | null;
  /** @nullable */
  parent_id?: number | null;
  is_purchasable?: boolean;
  popularity?: number;
  /** @nullable */
  default_amount?: number | null;
  /** @nullable */
  default_unit?: string | null;
}
