/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface AddMasterProductRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  unit?: string | null;
  amount?: number;
  category_id?: number;
  /** @nullable */
  image_url?: string | null;
  /** @nullable */
  brand?: string | null;
  /** @nullable */
  child_product_ids?: number[] | null;
}
