/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { BasePriceModel } from './basePriceModel';
import type { DiscountPriceModel } from './discountPriceModel';
import type { ProductAvailabilityModel } from './productAvailabilityModel';

export interface AddOrChangePriceRequest {
  shop_id?: number;
  base_price?: BasePriceModel;
  discount_price?: DiscountPriceModel;
  product_availability?: ProductAvailabilityModel;
  /** @nullable */
  location?: string | null;
}
