/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { AddOrChangePriceRequest } from './addOrChangePriceRequest';

export interface AddOrChangePriceBulkRequest {
  /** @nullable */
  product_ids?: number[] | null;
  price_model?: AddOrChangePriceRequest;
}
