/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { DiscountPriceModel } from './discountPriceModel';
import type { ProductValidityModel } from './productValidityModel';

export interface AddOrChangePriceRequest {
  shop_id?: number;
  price?: number;
  discount_price?: DiscountPriceModel;
  validity?: ProductValidityModel;
  /** @nullable */
  location?: string | null;
}
