/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { CartCategoryItem } from './cartCategoryItem';
import type { CartProductItem } from './cartProductItem';

export interface AddToCartRequest {
  /** @nullable */
  category_items?: CartCategoryItem[] | null;
  /** @nullable */
  product_items?: CartProductItem[] | null;
}
