/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { CategoryDto } from './categoryDto';
import type { ShopProductDto } from './shopProductDto';

export interface AdminCategoryDto {
  category?: CategoryDto;
  /** @nullable */
  available_shops?: number[] | null;
  cheapest_from_category?: ShopProductDto;
}
