/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface ArchivedCartProductDetail {
  product_id?: number;
  /** @nullable */
  barcodes?: string[] | null;
  /** @nullable */
  name?: string | null;
  amount?: number;
  /** @nullable */
  brand?: string | null;
  /** @nullable */
  unit?: string | null;
  /** @nullable */
  image_url?: string | null;
  /** @nullable */
  category_id?: number | null;
}
