/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ArchivedCartProduct } from './archivedCartProduct';

export interface ArchivedCartDto {
  cart_id?: number;
  /** @nullable */
  owner_id?: string | null;
  /** @nullable */
  barcodes?: ArchivedCartProduct[] | null;
  created_at?: string;
  shop_id?: number;
  total_price?: number;
  price_difference?: number;
}
