/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { CartCategoryModel } from './cartCategoryModel';
import type { ShopExtendedDto } from './shopExtendedDto';
import type { ShopItemDto } from './shopItemDto';

export interface ArchivedCartModel {
  cart_id?: number;
  /** @nullable */
  owner_id?: string | null;
  /** @nullable */
  categories?: CartCategoryModel[] | null;
  /** @nullable */
  barcodes?: ShopItemDto[] | null;
  created_at?: string;
  shop?: ShopExtendedDto;
  total_price?: number;
  price_difference?: number;
}
