/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { AvailableProductsFromCategoryDto } from './availableProductsFromCategoryDto';

export interface AvailableCategoriesForShopDto {
  /** @nullable */
  categories?: AvailableProductsFromCategoryDto[] | null;
  shop_id?: number;
}
