/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { PatchProductBulkDto } from './patchProductBulkDto';

export interface BulkUpdateRequest {
  /** @nullable */
  ids?: number[] | null;
  model?: PatchProductBulkDto;
}
