/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';
import type { CartComparisonProductType } from './cartComparisonProductType';
import type { DiscountPriceDto } from './discountPriceDto';

export interface CartComparisonProductDto {
  detail?: ProductDto;
  type?: CartComparisonProductType;
  shop_id?: number;
  quantity?: number;
  price?: number;
  total_price?: number;
  discount_price?: DiscountPriceDto;
  original_product_detail?: ProductDto;
}
