/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export type CartComparisonProductType =
  (typeof CartComparisonProductType)[keyof typeof CartComparisonProductType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CartComparisonProductType = {
  Original: 'Original',
  ReplacedWithCategoryProduct: 'ReplacedWithCategoryProduct',
  CategoryReplacedWithProduct: 'CategoryReplacedWithProduct',
  Missing: 'Missing',
} as const;
