/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface CreateProductDto {
  /** @nullable */
  name?: string | null;
  amount?: number;
  /** @nullable */
  unit?: string | null;
  /** @nullable */
  barcode?: string | null;
  /** @nullable */
  scanned_barcode?: string | null;
  /** @nullable */
  brand?: string | null;
  /** @nullable */
  category_id?: number | null;
  /** @nullable */
  image_base64?: string | null;
}
