/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface DiscountPriceModel {
  price?: number;
  /** @nullable */
  percentage_discount?: number | null;
  valid_from?: string;
  valid_to?: string;
}
