/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { DiscountPriceImportEntryDto } from './discountPriceImportEntryDto';

export interface DiscountPriceImportBatchDto {
  batch_id?: number;
  shop_id?: number;
  /** @nullable */
  location?: string | null;
  date_submitted?: string;
  valid_from?: string;
  valid_to?: string;
  discount_count?: number;
  /** @nullable */
  discounts?: DiscountPriceImportEntryDto[] | null;
}
