/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode = {
  None: 'None',
  NotFound: 'NotFound',
  Conflict: 'Conflict',
  Validation: 'Validation',
  HeaderValidation: 'HeaderValidation',
  InvalidState: 'InvalidState',
  AdapterError: 'AdapterError',
  Internal: 'Internal',
  Serialization: 'Serialization',
} as const;
