/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { AdminCategoryDto } from './adminCategoryDto';

export interface GetCategoryAdminResponse {
  all_count?: number;
  count?: number;
  /** @nullable */
  all_categories?: AdminCategoryDto[] | null;
}
