/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export type GetCategoriesParams = {
  category_name?: string;
  is_leaf?: boolean;
  is_purchasable?: boolean;
  has_image?: boolean;
  popularity?: number;
  Limit?: number;
  Offset?: number;
};
