/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { PriceDto } from './priceDto';
import type { DiscountPriceDto } from './discountPriceDto';
import type { DiscountHistoryPriceDto } from './discountHistoryPriceDto';

export interface GetProductPricesResponse {
  current_price?: PriceDto;
  /** @nullable */
  price_history?: PriceDto[] | null;
  current_discount?: DiscountPriceDto;
  /** @nullable */
  discount_history?: DiscountHistoryPriceDto[] | null;
}
