/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';

export interface GetProductsManagementAdminResponse {
  /** @nullable */
  all_products_with_not_leaf_category?: ProductDto[][] | null;
  /** @nullable */
  products_with_not_set_category?: ProductDto[] | null;
}
