/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { OrderType } from './orderType';

export type GetProductsParams = {
  search_type?: OrderType;
  search?: string;
  category_id?: number;
  restricted_shops?: number[];
  has_image?: boolean;
  is_category_checked?: boolean;
  is_master_product?: boolean;
  created_after?: string;
  Limit?: number;
  Offset?: number;
};
