/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export type OrderType = (typeof OrderType)[keyof typeof OrderType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderType = {
  None: 'None',
  TrigramSimilarity: 'TrigramSimilarity',
  Semantic: 'Semantic',
  CreatedDate: 'CreatedDate',
  FullTextSearch: 'FullTextSearch',
  HybridSearch: 'HybridSearch',
} as const;
