/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface PatchCategoryDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  parent_id?: number | null;
  /** @nullable */
  is_purchasable?: boolean | null;
  /** @nullable */
  popularity?: number | null;
  /** @nullable */
  base64_image?: string | null;
  /** @nullable */
  default_unit?: string | null;
  /** @nullable */
  default_amount?: number | null;
}
