/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { DiscountImportActionEnum } from './discountImportActionEnum';

export interface PatchDiscountImportRequest {
  action?: DiscountImportActionEnum;
  /** @nullable */
  product_id?: number | null;
  /** @nullable */
  shop_id?: number | null;
}
