/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductCartDtoProductDto } from './productCartDtoProductDto';

export interface ProductCartDto {
  /** @nullable */
  specific_products?: ProductCartDtoProductDto[] | null;
  total_price?: number;
}
