import type { CartComparisonProductDto } from './cartComparisonProductDto';
import type { MissingItemVariant } from './missingItemVariant';
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopExtendedDto } from './shopExtendedDto';

export interface ProductCartShopVariantDto {
  shop?: ShopExtendedDto;
  /** @nullable */
  product_items?: CartComparisonProductDto[] | null;
  /** @nullable */
  category_items?: CartComparisonProductDto[] | null;
  /** @nullable */
  missing_items?: MissingItemVariant[] | null;
  total_price?: number;
}
