/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { Error } from './error';

export interface ProductImportResult {
  all_count?: number;
  count?: number;
  count_of_products_with_barcode_update_product?: number;
  count_of_products_with_barcode_create_product?: number;
  count_of_products_without_barcode?: number;
  products_with_not_leaf_category_count?: number;
  /** @nullable */
  errors?: Error[] | null;
}
