/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface ProductCartItemDto {
  /** @minLength 1 */
  barcode: string;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  quantity?: number;
}
