/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';
import type { ShopPriceDto } from './shopPriceDto';

export interface ShopCategoryPriceDto {
  shop_id?: number;
  product?: ProductDto;
  price?: ShopPriceDto;
  product_id?: number;
}
