import type { DiscountPriceDto } from './discountPriceDto';
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductWithExtendedCategoryDto } from './productWithExtendedCategoryDto';

export interface ShopItemWithExtendedCategoryDto {
  detail?: ProductWithExtendedCategoryDto;
  shop_id?: number;
  price?: number;
  discount_price?: DiscountPriceDto;
}
