/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopItemDto } from './shopItemDto';

export interface ShopCartCategory {
  category_id?: number;
  /** @nullable */
  category_name?: string | null;
  cheapest_product?: ShopItemDto;
}
