/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { DiscountPriceDto } from './discountPriceDto';

export interface ShopPriceDto {
  shop_id?: number;
  price?: number;
  actual_price?: number;
  discount_price?: DiscountPriceDto;
  /** @nullable */
  valid_from?: string | null;
  /** @nullable */
  valid_to?: string | null;
  /** @nullable */
  scanned_image_url?: string | null;
}
