/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface ShortArchivedHybridCartDto {
  cart_id?: number;
  selected_shop_id?: number;
  total_price?: number;
  price_difference?: number;
  created_at?: string;
}
