/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';

export interface UnitProducts {
  /** @nullable */
  unit?: string | null;
  /** @nullable */
  products?: ProductDto[] | null;
}
