/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface UpdateShopModel {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  image_url?: string | null;
}
