/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { UserRole } from './userRole';

export interface UploadUserRequest {
  /** @nullable */
  email?: string | null;
  role?: UserRole;
}
