/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { UserMaintenanceDto } from './userMaintenanceDto';

export interface UserMaintenanceDtoGenericPagedResult {
  count?: number;
  /** @nullable */
  items?: UserMaintenanceDto[] | null;
}
