/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { DiscountPriceDto } from './discountPriceDto';
import type { ProductValidityModel } from './productValidityModel';

export interface AddOrChangePriceRequest {
  shop_id?: number;
  /** @nullable */
  price?: number | null;
  discount_price?: DiscountPriceDto;
  validity?: ProductValidityModel;
  /** @nullable */
  location?: string | null;
}
