import type { DiscountPriceDto } from './discountPriceDto';
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductHarvesterImportDto } from './productHarvesterImportDto';

export interface AddProductRequest {
  product?: ProductHarvesterImportDto;
  shop_id?: number;
  price?: number;
  discount_price?: DiscountPriceDto;
  /** @nullable */
  location?: string | null;
}
