/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductImportDto } from './productImportDto';
import type { DiscountPriceDto } from './discountPriceDto';

export interface AddProductRequest {
  product?: ProductImportDto;
  shop_id?: number;
  price?: number;
  discount_price?: DiscountPriceDto;
}
