/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { HybridCartCategoryItem } from './hybridCartCategoryItem';
import type { HybridCartProductItem } from './hybridCartProductItem';

export interface AddToHybridCartRequest {
  /** @nullable */
  category_items?: HybridCartCategoryItem[] | null;
  /** @nullable */
  product_items?: HybridCartProductItem[] | null;
}
