/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopCartModel } from './shopCartModel';

export interface ArchivedCartModel {
  cart_id?: number;
  /** @nullable */
  owner_id?: string | null;
  /** @nullable */
  categories?: number[] | null;
  /** @nullable */
  barcodes?: number[] | null;
  created_at?: string;
  selected_shop_id?: number;
  selected_cart?: ShopCartModel;
  price_difference?: number;
}
