/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface ArchivedCartDto {
  cart_id?: number;
  /** @nullable */
  owner_id?: string | null;
  /** @nullable */
  categories?: number[] | null;
  /** @nullable */
  barcodes?: number[] | null;
  created_at?: string;
  /** @nullable */
  all_carts_at_creation_time?: string | null;
}
