/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ArchivedHybridCartProductDetail } from './archivedHybridCartProductDetail';
import type { HybridCartComparisonProductType } from './hybridCartComparisonProductType';

export interface ArchivedHybridCartProduct {
  detail?: ArchivedHybridCartProductDetail;
  type?: HybridCartComparisonProductType;
  shop_id?: number;
  quantity?: number;
  price?: number;
  total_price?: number;
}
