/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopItemDto } from './shopItemDto';

export interface AvailableProductsFromCategoryDto {
  category_id?: number;
  /** @nullable */
  products?: ShopItemDto[] | null;
}
