/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface BrigaderReviewListItem {
  barcode?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  unit?: string | null;
  amount?: number;
  price?: number;
  /** @nullable */
  brand?: string | null;
  is_checked?: boolean;
}
