/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface BrigaderReviewListItemDto {
  /** @nullable */
  readonly barcode?: string | null;
  /** @nullable */
  readonly name?: string | null;
  /** @nullable */
  readonly unit?: string | null;
  readonly amount?: number;
  readonly price?: number;
  /** @nullable */
  readonly brand?: string | null;
  /** @nullable */
  readonly resolved_by_user?: string | null;
  readonly is_checked?: boolean;
}
