/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { CategoryExtendedDto } from './categoryExtendedDto';
import type { ProductDto } from './productDto';

export interface CartCategoryDto {
  category?: CategoryExtendedDto;
  cheapest?: ProductDto;
  price?: number;
  normalized_price?: number;
}
