import type { CartCategoryDto } from './cartCategoryDto';
import type { CartProductDto } from './cartProductDto';
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopExtendedDto } from './shopExtendedDto';

export interface CartDto {
  shop?: ShopExtendedDto;
  /** @nullable */
  specific_products?: CartProductDto[] | null;
  /** @nullable */
  categories?: CartCategoryDto[] | null;
  total_price?: number;
  normalized_total_price?: number;
  /** @nullable */
  available_shop_ids?: number[] | null;
}
