/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface CategoryDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  image_url?: string | null;
  /** @nullable */
  parent_id?: number | null;
  is_purchasable?: boolean;
  popularity?: number;
  /** @nullable */
  path_from_root?: string[] | null;
  /** @nullable */
  path_from_root_numeric?: number[] | null;
}
