/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface CategoryDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  parent_id?: number | null;
}
