/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface CategoryExtendedWithPathDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  parent_id?: number | null;
  id?: number;
  /** @nullable */
  path_from_root?: string | null;
  /** @nullable */
  path_from_root_numeric?: string | null;
}
