/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export type DiscountImportActionEnum =
  (typeof DiscountImportActionEnum)[keyof typeof DiscountImportActionEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DiscountImportActionEnum = {
  None: 'None',
  Reject: 'Reject',
  Accept: 'Accept',
} as const;
