/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface DiscountPriceDto {
  price?: number;
  valid_from?: string;
  valid_to?: string;
}
