/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface DiscountPriceImportEntryDto {
  import_id?: number;
  /** @nullable */
  title?: string | null;
  new_discount_price?: number;
  /** @nullable */
  percentage_discount?: number | null;
  amount?: number;
  /** @nullable */
  unit?: string | null;
}
