/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';
import type { ShopPriceDto } from './shopPriceDto';
import type { DiscountPriceDto } from './discountPriceDto';

export interface DiscountShopItemDto {
  detail?: ProductDto;
  /** @nullable */
  barcode?: string | null;
  /** @nullable */
  shops_prices?: ShopPriceDto[] | null;
  shop_id?: number;
  price?: number;
  actual_price?: number;
  discount_price?: DiscountPriceDto;
  /** @nullable */
  available_shop_ids?: number[] | null;
}
