/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { BrigaderReviewListItem } from './brigaderReviewListItem';

export interface GetBrigaderReviewListResponse {
  shop_id?: number;
  /** @nullable */
  products_to_check?: BrigaderReviewListItem[] | null;
  created_at?: string;
  calendar_week?: number;
}
