/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { AddCategoryExtendedWithPathDto } from './addCategoryExtendedWithPathDto';

export interface GetCategoryResponse {
  count?: number;
  /** @nullable */
  categories?: AddCategoryExtendedWithPathDto[] | null;
}
