/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { CategoryDto } from './categoryDto';

export interface GetCategoryAdminResponse {
  all_count?: number;
  /** @nullable */
  all_categories?: CategoryDto[] | null;
}
