/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { CategoryItem } from './categoryItem';
import type { ProductItem } from './productItem';

export interface GetCartComparisonRequest {
  /** @nullable */
  categories?: CategoryItem[] | null;
  /** @nullable */
  products?: ProductItem[] | null;
}
