/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export type GetCartComparisonParams = {
  CategoryIds?: number[];
  Barcodes?: number[];
};
