/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { DiscountPriceImportBatchDto } from './discountPriceImportBatchDto';

export interface GetDiscountPriceImportsResponse {
  all_count?: number;
  /** @nullable */
  discount_import_batches?: DiscountPriceImportBatchDto[] | null;
}
