/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export type GetDiscountPriceImportsParams = {
  resolved?: boolean;
  shop_id?: number;
  Limit?: number;
  Offset?: number;
};
