/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { DiscountShopItemDto } from './discountShopItemDto';

export interface GetDiscountsResponse {
  count?: number;
  /** @nullable */
  products?: DiscountShopItemDto[] | null;
}
