/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export type GetProductsAdminParams = {
  category_id?: number;
  search?: string;
  restricted_shops?: number[];
  Limit?: number;
  Offset?: number;
};
