/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopProductDto } from './shopProductDto';

export interface GetProductsSemanticResponse {
  count?: number;
  /** @nullable */
  products?: ShopProductDto[] | null;
}
