/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ItemListGroupedByBarcodeDto } from './itemListGroupedByBarcodeDto';

export interface GetProductsAdminResponse {
  count?: number;
  /** @nullable */
  products?: ItemListGroupedByBarcodeDto[] | null;
}
