/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductCartShopVariantDto } from './productCartShopVariantDto';

export interface GetProductCartComparisonResponse {
  /** @nullable */
  carts?: ProductCartShopVariantDto[] | null;
}
