/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopItemListDto } from './shopItemListDto';

export interface GetProductsResponse {
  /** @nullable */
  products?: ShopItemListDto[] | null;
}
