/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export type GetProductsParams = {
  category_id?: number;
  search?: string;
  restricted_shops?: number[];
  has_image?: boolean;
  is_barcode_checked?: boolean;
  is_category_checked?: boolean;
  Limit?: number;
  Offset?: number;
};
