/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopCategoryStat } from './shopCategoryStat';

export interface GetShopsStatsResponse {
  all_categories_count?: number;
  /** @nullable */
  categories_stats?: ShopCategoryStat[] | null;
}
