/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductExtendedDto } from './productExtendedDto';

export interface GetScannedProductsAdminResponse {
  count?: number;
  /** @nullable */
  products?: ProductExtendedDto[] | null;
}
