/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopExtendedDto } from './shopExtendedDto';

export interface GetShopsResponse {
  /** @nullable */
  shops?: ShopExtendedDto[] | null;
}
