/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { DiscountPriceImportEntryDto } from './discountPriceImportEntryDto';

export interface GetUnconfirmedDiscountsResponse {
  count?: number;
  /** @nullable */
  products?: DiscountPriceImportEntryDto[] | null;
}
