import type { CategoryDto } from './categoryDto';
import type { HybridCartComparisonProductDto } from './hybridCartComparisonProductDto';
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopExtendedDto } from './shopExtendedDto';

export interface HybridCartComparisonDto {
  shop?: ShopExtendedDto;
  /** @nullable */
  specific_products?: HybridCartComparisonProductDto[] | null;
  /** @nullable */
  missing_products?: HybridCartComparisonProductDto[] | null;
  /** @nullable */
  missing_categories?: CategoryDto[] | null;
  total_price?: number;
}
