/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';
import type { HybridCartComparisonProductType } from './hybridCartComparisonProductType';
import type { DiscountPriceDto } from './discountPriceDto';

export interface HybridCartComparisonProductDto {
  detail?: ProductDto;
  type?: HybridCartComparisonProductType;
  shop_id?: number;
  quantity?: number;
  price?: number;
  total_price?: number;
  discount_price?: DiscountPriceDto;
}
