/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export type HybridCartComparisonProductType =
  (typeof HybridCartComparisonProductType)[keyof typeof HybridCartComparisonProductType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HybridCartComparisonProductType = {
  Original: 'Original',
  ReplacedWithCategoryProduct: 'ReplacedWithCategoryProduct',
  CategoryReplacedWithProduct: 'CategoryReplacedWithProduct',
  Missing: 'Missing',
} as const;
