/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { CartProductDto } from './cartProductDto';
import type { CartCategoryDto } from './cartCategoryDto';

export interface HybridCartDto {
  /** @nullable */
  specific_products?: CartProductDto[] | null;
  /** @nullable */
  categories?: CartCategoryDto[] | null;
  total_price?: number;
}
