/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface PriceDto {
  price?: number;
  barcode?: number;
  shop_id?: number;
  change_requested?: string;
  /** @nullable */
  change_confirmed?: string | null;
  /** @nullable */
  status?: string | null;
}
