/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface PriceDto {
  barcode?: number;
  /** @nullable */
  change_confirmed?: string | null;
  change_requested?: string;
  price?: number;
  shop_id?: number;
  /** @nullable */
  status?: string | null;
}
