/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface ProductDto {
  amount?: number;
  barcode?: number;
  /** @nullable */
  brand?: string | null;
  category_id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  unit?: string | null;
}
