/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopExtendedDto } from './shopExtendedDto';
import type { ProductDto } from './productDto';
import type { MissingItemVariant } from './missingItemVariant';

export interface ProductCartShopVariantDto {
  shop?: ShopExtendedDto;
  /** @nullable */
  product_items?: ProductDto[] | null;
  /** @nullable */
  category_items?: ProductDto[] | null;
  /** @nullable */
  missing_items?: MissingItemVariant[] | null;
  total_price?: number;
}
