/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopCategory } from './shopCategory';
import type { ShopExtendedDto } from './shopExtendedDto';
import type { ShopItemDto } from './shopItemDto';

export interface ShopCart {
  /** @nullable */
  available_shop_ids?: number[] | null;
  /** @nullable */
  categories?: ShopCategory[] | null;
  normalized_total_price?: number;
  shop?: ShopExtendedDto;
  /** @nullable */
  specific_products?: ShopItemDto[] | null;
  total_price?: number;
}
