/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ShopExtendedDto } from './shopExtendedDto';
import type { ShopItemDto } from './shopItemDto';
import type { ShopCartCategory } from './shopCartCategory';

export interface ShopCart {
  shop?: ShopExtendedDto;
  /** @nullable */
  specific_products?: ShopItemDto[] | null;
  /** @nullable */
  categories?: ShopCartCategory[] | null;
  total_price?: number;
  normalized_total_price?: number;
  /** @nullable */
  available_shop_ids?: number[] | null;
}
