/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';

export interface ShopItemDto {
  detail?: ProductDto;
  price?: number;
  shop_id?: number;
}
