/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';
import type { DiscountPriceDto } from './discountPriceDto';

export interface ShopItemDto {
  detail?: ProductDto;
  shop_id?: number;
  price?: number;
  actual_price?: number;
  discount_price?: DiscountPriceDto;
}
