/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface UnitDto {
  original_amount?: number;
  /** @nullable */
  original_unit?: string | null;
  normalized_amount?: number;
  /** @nullable */
  normalized_unit?: string | null;
}
