/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface UploadProductImageRequest {
  /** @nullable */
  shop?: string | null;
  /** @nullable */
  barcode?: string | null;
  /** @nullable */
  file_base64?: string | null;
}
