/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Dolacna.Backend.Api
 * OpenAPI spec version: 1.0
 */

export interface WoltEntryDto {
  id?: number;
  /** @nullable */
  product?: string | null;
  shop_id?: number;
  /** @nullable */
  brand?: string | null;
  original_price?: number;
  current_price?: number;
  amount?: number;
  /** @nullable */
  unit?: string | null;
  /** @nullable */
  location?: string | null;
  date_scraped?: string;
  /** @nullable */
  date_resolved?: string | null;
  /** @nullable */
  state?: string | null;
}
