name: PR Checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔍 Check TypeScript
        run: npx tsc --noEmit

      - name: 🧹 Run linter
        run: npm run lint --if-present

      - name: 🧪 Run tests
        run: npm test --if-present

  build-preview:
    name: EAS Preview Build
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: |
      github.event.pull_request.base.ref == 'main' &&
      contains(github.event.pull_request.labels.*.name, 'preview-build')

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔐 Setup environment
        run: |
          cat << EOF > .env
          EXPO_PUBLIC_API_URL=${{ secrets.EXPO_PUBLIC_API_URL }}
          EXPO_PUBLIC_FIREBASE_API_KEY=${{ secrets.EXPO_PUBLIC_FIREBASE_API_KEY }}
          EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          EXPO_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.EXPO_PUBLIC_FIREBASE_PROJECT_ID }}
          EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          EXPO_PUBLIC_FIREBASE_APP_ID=${{ secrets.EXPO_PUBLIC_FIREBASE_APP_ID }}
          EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID=${{ secrets.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID }}
          EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID=${{ secrets.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID }}
          EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=${{ secrets.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID }}
          EXPO_PUBLIC_REVENUECAT_APPLE_API_KEY=${{ secrets.EXPO_PUBLIC_REVENUECAT_APPLE_API_KEY }}
          EXPO_PUBLIC_REVENUECAT_GOOGLE_API_KEY=${{ secrets.EXPO_PUBLIC_REVENUECAT_GOOGLE_API_KEY }}
          EXPO_PUBLIC_EAS_PROJECT_ID=${{ secrets.EXPO_PUBLIC_EAS_PROJECT_ID }}
          EOF

      - name: 🚀 Build preview
        run: eas build --platform all --profile preview --non-interactive --no-wait

      - name: 💬 Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview build started! Check the progress in [EAS Dashboard](https://expo.dev/accounts/adammartiska/projects/usetri/builds)'
            })
